printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: "none"
bracketSpacing: false
arrowParens: "always"
parser: "babel"
requirePragma: false
insertPragma: false
proseWrap: "preserve"
endOfLine: "crlf"

overrides:
    - files: 
      - "*.md" 
      - "*.yaml"
      - options:
        - tabWidth: 2
